title: AndroidScreencast
description: View and control your android device on PC
google_analytics: UA-30116628-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions

site:
  github:
    zip_url: https://github.com/xSAVIKx/AndroidScreencast/zipball/master
    tar_url: https://github.com/xSAVIKx/AndroidScreencast/tarball/master
